{
  "swagger": "2.0",
  "paths": {
    "/transactions": {
      "get": {
        "tags": [
          "Transaction"
        ],
        "summary": "Gets a transaction with the given id",
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Transaction"
            },
            "description": "OK"
          }
        },
        "parameters": [
          {
            "type": "integer",
            "required": true,
            "name": "id",
            "in": "path",
            "description": "Id of the transaction"
          }
        ],
        "operationId": "OMG.Watcher.Web.Controller.Transaction.get_transaction",
        "description": ""
      }
    },
    "/status": {
      "get": {
        "tags": [
          "Status"
        ],
        "summary": "Gets plasma network and Watcher status",
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/Status"
            },
            "description": "OK"
          }
        },
        "parameters": [],
        "operationId": "OMG.Watcher.Web.Controller.Status.get_status",
        "description": ""
      }
    },
    "/challenges": {
      "get": {
        "tags": [
          "Challenge"
        ],
        "summary": "Gets challenge for a given exit",
        "responses": {
          "400": {
            "schema": {
              "$ref": "#/definitions/BadRequestError"
            },
            "description": "Client Error"
          },
          "200": {
            "schema": {
              "$ref": "#/definitions/Challenge"
            },
            "description": "OK"
          }
        },
        "parameters": [
          {
            "type": "integer",
            "required": true,
            "name": "blknum",
            "in": "query",
            "description": "Block number of exiting utxo"
          },
          {
            "type": "integer",
            "required": true,
            "name": "txindex",
            "in": "query",
            "description": "Transaction index of exiting utxo"
          },
          {
            "type": "integer",
            "required": true,
            "name": "oindex",
            "in": "query",
            "description": "Output index of exiting utxo"
          }
        ],
        "operationId": "OMG.Watcher.Web.Controller.Challenge.challenge",
        "description": ""
      }
    },
    "/account/utxo/compose_exit": {
      "get": {
        "tags": [
          "Utxo"
        ],
        "summary": "Responds with exit for a given utxo",
        "responses": {
          "200": {
            "schema": {
              "$ref": "#/definitions/UtxoExit"
            },
            "description": "OK"
          }
        },
        "parameters": [
          {
            "type": "integer",
            "required": true,
            "name": "blknum",
            "in": "query",
            "description": "Number of block that the utxo was created in"
          },
          {
            "type": "integer",
            "required": true,
            "name": "txindex",
            "in": "query",
            "description": "Transaction index of the utxo"
          },
          {
            "type": "integer",
            "required": true,
            "name": "oindex",
            "in": "query",
            "description": "Output index of the utxo"
          }
        ],
        "operationId": "OMG.Watcher.Web.Controller.Utxo.compose_utxo_exit",
        "description": ""
      }
    }
  },
  "info": {
    "version": "1.0",
    "title": "OMG Watcher"
  },
  "definitions": {
    "Utxos": {
      "type": "array",
      "title": "Array of utxos",
      "items": {
        "$ref": "#/definitions/Utxo"
      }
    },
    "UtxoExit": {
      "type": "object",
      "title": "Utxo exit",
      "required": [
        "sigs",
        "proof",
        "txbytes",
        "utxo_pos"
      ],
      "properties": {
        "utxo_pos": {
          "type": "integer",
          "description": "Utxo position"
        },
        "txbytes": {
          "type": "string",
          "description": "Signed hash of transaction"
        },
        "sigs": {
          "type": "string",
          "description": "Signatures of users that confirmed transaction"
        },
        "proof": {
          "type": "string",
          "description": "Merkle proof that transaction that produced the utxo is contained in a childchain block"
        }
      },
      "example": {
        "utxo_pos": 10001001,
        "txbytes": "F84701018080808094000000000000000000000000000000000000000094D27EB36B73F275E3F7CD20A510710F763DE3BF366E94000000000000000000000000000000000000000080",
        "sigs": "7C29FB8327F60BBFC6201DF2FBAAA8D22E5C0CA3D1EB5FF0D37ECDAF61E507FE77DED514AA42A622E5682BF692B33E60D292425C531109841C67B5BD86876CDE1C0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "proof": "CEDB8B31D1E4CB72EC267A8B27C42C4D9982C3F3950D88003F44B3A797202D848025356282CA1C28CBD51FBF7D8E9187AA85F628D054B2C2233AA83BCAEF1F0EB4C11951957C6F8F642C4AF61CD6B24640FEC6DC7FC607EE8206A99E92410D3021DDB9A356815C3FAC1026B6DEC5DF3124AFBADB485C9BA5A3E3398A04B7BA85E58769B32A1BEAF1EA27375A44095A0D1FB664CE2DD358E7FCBFB78C26A193440EB01EBFC9ED27500CD4DFC979272D1F0913CC9F66540D7E8005811109E1CF2D887C22BD8750D34016AC3C66B5FF102DACDD73F6B014E710B51E8022AF9A1968FFD70157E48063FC33C97A050F7F640233BF646CC98D9524C6B92BCF3AB56F839867CC5F7F196B93BAE1E27E6320742445D290F2263827498B54FEC539F756AFCEFAD4E508C098B9A7E1D8FEB19955FB02BA9675585078710969D3440F5054E0F9DC3E7FE016E050EFF260334F18A5D4FE391D82092319F5964F2E2EB7C1C3A5F8B13A49E282F609C317A833FB8D976D11517C571D1221A265D25AF778ECF8923490C6CEEB450AECDC82E28293031D10C7D73BF85E57BF041A97360AA2C5D99CC1DF82D9C4B87413EAE2EF048F94B4D3554CEA73D92B0F7AF96E0271C691E2BB5C67ADD7C6CAF302256ADEDF7AB114DA0ACFE870D449A3A489F781D659E8BECCDA7BCE9F4E8618B6BD2F4132CE798CDC7A60E7E1460A7299E3C6342A579626D2"
      },
      "description": "Can be submitted to rootchain to initiate an utxo exit"
    },
    "Utxo": {
      "type": "object",
      "title": "Utxo",
      "required": [
        "txbytes",
        "oindex",
        "txindex",
        "blknum",
        "amount",
        "currency"
      ],
      "properties": {
        "txindex": {
          "type": "integer",
          "description": "Number of transaction that created the utxo"
        },
        "txbytes": {
          "type": "string",
          "description": "Signed hash of transaction that created the utxo"
        },
        "oindex": {
          "type": "integer",
          "description": "Output index in the transaction"
        },
        "currency": {
          "type": "string",
          "description": "Currency of the utxo"
        },
        "blknum": {
          "type": "integer",
          "description": "Number of childchain block that contains transaction that created the utxo"
        },
        "amount": {
          "type": "integer",
          "description": "Amount of the currency"
        }
      },
      "example": {
        "txindex": 1,
        "txbytes": "F8CF0101808080809400000000000000000000000000000000000000009459D87A1B128920C828C2648C9211F6626A9C82F28203E894000000000000000000000000000000000000000080B84196BE9F44CE42D5A20DC382AAB8C940BD25E8A9A7E50B9CE976ADEEB7EDE1348B1F7BBA11C5EB235CE732AD960EF7E71330C34C137A5D2C09FA9A2F8F680911CA1CB8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "oindex": 0,
        "currency": "0000000000000000000000000000000000000000",
        "blknum": 1000,
        "amount": 10
      }
    },
    "Transaction": {
      "type": "object",
      "title": "Transaction",
      "required": [
        "spender2",
        "spender1",
        "sig2",
        "sig1",
        "txindex",
        "txblknum",
        "amount2",
        "newowner2",
        "amount1",
        "newowner1",
        "cur12",
        "oindex2",
        "txindex2",
        "blknum2",
        "oindex1",
        "txindex1",
        "blknum1",
        "txid"
      ],
      "properties": {
        "txindex2": {
          "type": "integer",
          "description": "Transaction index of the second input utxo"
        },
        "txindex1": {
          "type": "integer",
          "description": "Transaction index of the first input utxo"
        },
        "txindex": {
          "type": "integer",
          "description": "Transaction index"
        },
        "txid": {
          "type": "string",
          "description": "Transaction id"
        },
        "txblknum": {
          "type": "integer",
          "description": "Number of block that the transaction is included in"
        },
        "spender2": {
          "type": "string",
          "description": "Address of owner of the second input utxo"
        },
        "spender1": {
          "type": "string",
          "description": "Address of owner of the first input utxo"
        },
        "sig2": {
          "type": "string",
          "description": "Signature of owner of the second input utxo"
        },
        "sig1": {
          "type": "string",
          "description": "Signature of owner of the first input utxo"
        },
        "oindex2": {
          "type": "integer",
          "description": "Output index of the second input utxo"
        },
        "oindex1": {
          "type": "integer",
          "description": "Output index of the first input utxo"
        },
        "newowner2": {
          "type": "string",
          "description": "Address of the owner of the second output utxo"
        },
        "newowner1": {
          "type": "string",
          "description": "Address of the owner of the first output utxo"
        },
        "cur12": {
          "type": "string",
          "description": "Currency of the transaction"
        },
        "blknum2": {
          "type": "integer",
          "description": "Childchain block number of the second input utxo"
        },
        "blknum1": {
          "type": "integer",
          "description": "Childchain block number of the first input utxo"
        },
        "amount2": {
          "type": "integer",
          "description": "Amount of currency in the second output utxo"
        },
        "amount1": {
          "type": "integer",
          "description": "Amount of currency in the first output utxo"
        }
      },
      "example": {
        "txindex2": 0,
        "txindex1": 2,
        "txindex": 1,
        "txid": "5DF13A6BF96DBCF6E66D8BABD6B55BD40D64D4320C3B115364C6588FC18C2A21",
        "txblknum": 3000,
        "spender2": "92EAD0DB732692FF887268DA965C311AC2C9005B",
        "spender1": "92EAD0DB732692FF887268DA965C311AC2C9005B",
        "sig2": "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "sig1": "F3050F1CC506480EFFBD78CB2FB21074AD3545564520F1E58F8F7BA1E37EF35450EB406A4173524CA0A6C4DE4D7EF7E814E161795EB8D852033E60F3539E61F71B",
        "oindex2": 1,
        "oindex1": 0,
        "newowner2": "0000000000000000000000000000000000000000",
        "newowner1": "B3256026863EB6AE5B06FA396AB09069784EA8EA",
        "cur12": "0000000000000000000000000000000000000000",
        "blknum2": 2000,
        "blknum1": 1000,
        "amount2": 2,
        "amount1": 1
      }
    },
    "Status": {
      "type": "object",
      "title": "Status",
      "required": [
        "eth_syncing",
        "last_mined_child_block_timestamp",
        "last_mined_child_block_number",
        "last_validated_child_block_number"
      ],
      "properties": {
        "last_validated_child_block_number": {
          "type": "integer",
          "description": "Number of last validated childchain block"
        },
        "last_mined_child_block_timestamp": {
          "type": "string",
          "description": "Timestamp when last childchain block was mined on the rootchain"
        },
        "last_mined_child_block_number": {
          "type": "string",
          "description": "Number of last childchain block that was mined on the rootchain"
        },
        "eth_syncing": {
          "type": "boolean",
          "description": "True only when watcher is not yet synced with the rootchain"
        }
      },
      "example": {
        "last_validated_child_block_number": 10000,
        "last_mined_child_block_timestamp": 1535031020,
        "last_mined_child_block_number": 11000,
        "eth_syncing": true
      },
      "description": "Plasma network and Watcher status"
    },
    "Challenge": {
      "type": "object",
      "title": "Exit challenge",
      "required": [
        "sigs",
        "proof",
        "txbytes",
        "eutxoindex",
        "cutxopos"
      ],
      "properties": {
        "txbytes": {
          "type": "string",
          "description": "Transaction that spends exiting utxo"
        },
        "sigs": {
          "type": "string",
          "description": "Signatures of users that participated in the challenging transaction"
        },
        "proof": {
          "type": "string",
          "description": "Proof that transaction is contained in a block"
        },
        "eutxoindex": {
          "type": "string",
          "description": "Exiting utxo position"
        },
        "cutxopos": {
          "type": "string",
          "description": "Challenging utxo position"
        }
      },
      "example": {
        "txbytes": "F849822AF880808080809400000000000000000000000000000000000000009489F5AD3F771617E853451A93F7A73E48CF5550D104948CE5C73FD5BEFFE0DCBCB6AFE571A2A3E73B043C03",
        "sigs": "6BFB9B2DBE3201BDC48072E69148A0ED9AF3E01D87772C8A77A478F998CEB5236B0AE64FAB3C21C078188B162D86913010A988E4B0CE68EE95D86783008FD9C71B0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "proof": "0000000000000000000000000000000000000000000000000000000000000000AD3228B676F7D3CD4284A5443F17F1962B36E491B30A40B2405849E597BA5FB5B4C11951957C6F8F642C4AF61CD6B24640FEC6DC7FC607EE8206A99E92410D3021DDB9A356815C3FAC1026B6DEC5DF3124AFBADB485C9BA5A3E3398A04B7BA85E58769B32A1BEAF1EA27375A44095A0D1FB664CE2DD358E7FCBFB78C26A193440EB01EBFC9ED27500CD4DFC979272D1F0913CC9F66540D7E8005811109E1CF2D887C22BD8750D34016AC3C66B5FF102DACDD73F6B014E710B51E8022AF9A1968FFD70157E48063FC33C97A050F7F640233BF646CC98D9524C6B92BCF3AB56F839867CC5F7F196B93BAE1E27E6320742445D290F2263827498B54FEC539F756AFCEFAD4E508C098B9A7E1D8FEB19955FB02BA9675585078710969D3440F5054E0F9DC3E7FE016E050EFF260334F18A5D4FE391D82092319F5964F2E2EB7C1C3A5F8B13A49E282F609C317A833FB8D976D11517C571D1221A265D25AF778ECF8923490C6CEEB450AECDC82E28293031D10C7D73BF85E57BF041A97360AA2C5D99CC1DF82D9C4B87413EAE2EF048F94B4D3554CEA73D92B0F7AF96E0271C691E2BB5C67ADD7C6CAF302256ADEDF7AB114DA0ACFE870D449A3A489F781D659E8BECCDA7BCE9F4E8618B6BD2F4132CE798CDC7A60E7E1460A7299E3C6342A579626D2",
        "eutxoindex": "200001001",
        "cutxopos": "100001001"
      }
    },
    "BadRequestError": {
      "type": "object",
      "title": "Bad request",
      "required": [
        "error"
      ],
      "properties": {
        "error": {
          "type": "string",
          "description": "The message of the error raised"
        }
      },
      "example": {
        "error": "exit is valid"
      },
      "description": "Erroneous request from the user"
    }
  }
}